apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-models-pv
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=4.1
  nfs:
    server: 192.168.1.52
    path: /llm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-models-pv
  resources:
    requests:
      storage: 5Ti

