apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: containeroo
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.containeroo.ch
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: local-path-storage
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: containeroo
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    storageClass:
      create: true
      name: local-path
      defaultClass: true
