apiVersion: v1
kind: ServiceAccount
metadata:
  name: lcd-writer
  namespace: lcd-writer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lcd-writer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lcd-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lcd-writer
subjects:
  - kind: ServiceAccount
    name: lcd-writer
    namespace: lcd-writer

